### ISSUE TITLE
Fix Item Detail View Page

### ISSUE THREAD

**Issue by liam-strand** [JumboCode/theatre-at-first#59]
The Item Detail View Page is doing great, but the data is presented manually, instead of reusing our component that was made earlier. @nehirozden has done some work so you should talk to her about it

**Comment by nehirozden** [comment]
The issue arose when importing the item view component to the page instead of just doing it ourselves. When it was added, it messed up the image carousel -- so that's the first thing to fix with the style. The second thing is making the comments style look better, which deals with the actual item view page styling as well as fixing some of the styling in the comments component (comment-comp-single-view.tsx).

**Comment by ShepardRodgers** [comment]
https://www.figma.com/file/IMqLmV0zw99WwEphQijEa8/Theatre%40First-%7C-JumboCode-%7C-23---24?type=design&node-id=80-36135&mode=design&t=ftiqu2ttSMwZUexA-4
